'use client';

import { useState, useEffect, type CSSProperties } from 'react';
import { ClipboardList, ChartColumn, BookMarked, CalendarDays, Settings, Coins, FileText, Play, ChevronLeft, ChevronRight, X, Check, GraduationCap, Sparkles } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarContent } from '@/components/ui/sidebar';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

const crops = { banner:[310,95,415,125], avatar:[759,110,95,96], neon:[1060,200,149,97], palette:[1224,199,151,99], font:[1060,344,149,85], cursor:[1225,344,150,85], alternate:[1060,476,149,86], icons:[1225,476,150,86] };
function Art({name,className=''}:{name:keyof typeof crops,className?:string}) { const [x,y,w,h]=crops[name]; return <div role="img" aria-label={name==='avatar'?'Avatar de Ana Silva':name==='banner'?'Ilustração colorida de uma estudante':name} className={`art ${className}`} style={{aspectRatio:`${w}/${h}`,backgroundImage:'url(/reference.png)',backgroundSize:`${1408/w*100}% ${768/h*100}%`,backgroundPosition:`${x/(1408-w)*100}% ${y/(768-h)*100}%`}}/>; }
const products = [{art:'neon',title:'Tema Neon',price:500},{art:'palette',title:'Paletas de cores',price:100},{art:'font',title:'Fontes criativas',price:100},{art:'cursor',title:'Cursor estrela',price:100},{art:'alternate',title:'Banners diferentes',price:100},{art:'icons',title:'Pack de ícones',price:100}] as const;
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
export default function Home(){
 const [editing,setEditing]=useState(true),[coins,setCoins]=useState(2450),[owned,setOwned]=useState<string[]>([]),[theme,setTheme]=useState(false),[color,setColor]=useState(false),[font,setFont]=useState(false),[banner,setBanner]=useState(false),[cursor,setCursor]=useState(false),[icons,setIcons]=useState(false),[avatar,setAvatar]=useState(false),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<string|null>(null),[date,setDate]=useState(new Date(2026,8,1)),[selected,setSelected]=useState(8),[active,setActive]=useState('Tarefas');
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool={name:'set_customization_panel',description:'Abre ou fecha o painel de personalização da Sala do Aluno.',inputSchema:{type:'object',properties:{open:{type:'boolean'}},required:['open'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('open' in input)||typeof input.open!=='boolean')throw new Error('Informe open como booleano.');setEditing(input.open);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {open:input.open};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 const days=new Date(date.getFullYear(),date.getMonth()+1,0).getDate(), offset=date.getDay();
 function buy(p:typeof products[number]) { if(!owned.includes(p.art)){if(coins<p.price){setNotice('Você ainda não tem moedas suficientes.');return}setCoins(coins-p.price);setOwned([...owned,p.art]);} ({neon:()=>setTheme(!theme),palette:()=>setColor(!color),font:()=>setFont(!font),cursor:()=>setCursor(!cursor),alternate:()=>setBanner(!banner),icons:()=>setIcons(!icons)})[p.art]();setNotice(`${p.title}: personalização aplicada!`); }
 return <div className={`school ${theme?'neon':''} ${font?'creative':''} ${cursor?'star-cursor':''}`} style={{'--primary':color?'#8b4acb':'#ff7900'} as CSSProperties}>
 <SidebarProvider><Sidebar collapsible="none" className="school-sidebar"><a className="brand" href="/">Sala do<strong>Aluno<span>.</span></strong></a><SidebarContent><nav aria-label="Navegação principal">{[{title:'Chamada',icon:ClipboardList},{title:'Boletim',icon:ChartColumn},{title:'Tarefas',icon:BookMarked},{title:'Calendário',icon:CalendarDays}].map(({title,icon:Icon})=><button key={title} className={`nav-item ${active===title?'active':''}`} onClick={()=>{setActive(title);if(title==='Chamada'||title==='Boletim')setDialog(title);else document.getElementById(title==='Tarefas'?'tarefas':'calendario')?.scrollIntoView({behavior:'smooth',block:'nearest'});}}><Icon strokeWidth={1.7} className={icons?'special-icon':''}/><span>{title}</span></button>)}</nav></SidebarContent><div className="school-sign"><GraduationCap size={22}/><span>Escola do Saber</span></div></Sidebar>
 <main className="workspace"><header className="top-row"><Art name={banner?'alternate':'banner'} className="main-banner"/><div className="profile card"><button className="avatar-button" aria-label="Trocar avatar" onClick={()=>setAvatar(!avatar)}>{avatar?<span className="emoji-avatar">👩🏽‍🚀</span>:<Art name="avatar"/>}</button><div className="profile-info"><h1>Ana Silva</h1><p>Nível 5</p><p className="balance">Moedas: <strong>{coins}</strong> <Coins size={20}/></p></div><button className={`edit-button ${editing?'is-open':''}`} aria-expanded={editing} aria-controls="personalizacao" onClick={()=>setEditing(!editing)}>Modo Edição <Settings size={21}/></button></div></header>
 <div className="dashboard"><div className="primary-column"><section id="tarefas"><div className="section-heading"><h2>Cards das Tarefas do Dia</h2><span>2 atividades</span></div><div className="task-grid">{[{title:'Atividade de matemática 1',date:'10 de setembro',progress:72},{title:'Atividade de matemática 2',date:'12 de setembro',progress:60}].map((task,i)=><article className="task card" key={task.title}><h3>{task.title}</h3><p className="deadline">Entrega: <span>{task.date}</span></p><div className="progress-label">Progresso <span>{task.progress}%</span></div><Progress aria-label={`Progresso da atividade ${i+1}`} value={task.progress}/><button className="primary-button" onClick={()=>setDialog(task.title)}>Continuar Atividade</button></article>)}</div></section>
 <section className="schedule"><div className="section-heading"><h2>Cronograma do Dia</h2><span>Terça, 8 de setembro</span></div>{[{time:'09:30',end:'10:30',teacher:'Prof. Carlos · História',lesson:'Capítulo 3 — PDF',color:'pink',video:true},{time:'13:00',end:'14:00',teacher:'Prof. Carlos · História',lesson:'Vídeo Aula',color:'yellow',video:false},{time:'14:30',end:'15:30',teacher:'Profa. Júlia · Matemática',lesson:'Exercícios de frações',color:'blue',video:true},{time:'16:00',end:'17:00',teacher:'Profa. Marina · Português',lesson:'Leitura e interpretação',color:'purple',video:false}].map(s=><button className={`schedule-row ${s.color}`} key={s.time} onClick={()=>setDialog(s.lesson)}><span className="time">{s.time}<span>— {s.end}</span></span><span className="lesson"><strong>{s.teacher}</strong><span>{s.lesson==='Vídeo Aula'?<Play size={19}/>:<FileText size={19}/>} {s.lesson}</span></span>{s.video&&<span className="video"><Play size={22}/><span>Vídeo Aula</span></span>}</button>)}</section><p className="day-note"><Sparkles size={17}/> Um passo de cada vez. Você está indo muito bem!</p></div>
 <div className="secondary-column"><section id="calendario"><div className="section-heading"><h2>Calendário</h2></div><div className="calendar card"><div className="month"><strong>{months[date.getMonth()]} {date.getFullYear()}</strong><div><button aria-label="Mês anterior" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()-1,1))}><ChevronLeft size={19}/></button><button aria-label="Próximo mês" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()+1,1))}><ChevronRight size={19}/></button></div></div><div className="calendar-grid">{['D','S','T','Q','Q','S','S'].map((d,i)=><span className="weekday" key={`w${i}`}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=><button className={selected===i+1?'selected':''} key={i} onClick={()=>setSelected(i+1)} aria-label={`${i+1} de ${months[date.getMonth()]}`} aria-pressed={selected===i+1}>{i+1}{[10,15,21].includes(i+1)&&<i/>}</button>)}</div><div className="calendar-foot"><span/> Dia selecionado: {selected} de {months[date.getMonth()].toLowerCase()}</div></div></section>
 <section className="reminders"><div className="section-heading"><h2>Lembretes</h2></div><div className="card reminder-card">{[{title:'Preparar o material de amanhã',sub:'Organize seus livros e cadernos',checked:true},{title:'Entregar a atividade de matemática',sub:'10 de setembro',checked:false},{title:'Evento da Sala do Aluno',sub:'21 de setembro',checked:false}].map((r,i)=><label className="reminder" key={i}><Checkbox defaultChecked={r.checked}/><span>{r.title}<small>{r.sub}</small></span></label>)}</div></section></div></div>
 {editing&&<aside className="customization card" id="personalizacao" aria-label="Personalizar sala"><div className="shop-heading"><strong>Deixe a sala do seu jeito</strong><button aria-label="Fechar personalização" onClick={()=>setEditing(false)}><X size={19}/></button></div><div className="product-grid">{products.map(p=><button className="product" key={p.art} onClick={()=>buy(p)}><Art name={p.art}/><strong>{p.title}</strong><small>{owned.includes(p.art)?<><Check size={12}/> Adquirido · alternar</>:<>Sala do Aluno · <span>{p.price} moedas</span></>}</small></button>)}</div><p className="shop-note">Use suas moedas para personalizar.</p></aside>}
 <div role="status" className={`toast ${notice?'visible':''}`} onClick={()=>setNotice('')}>{notice}<button aria-label="Dispensar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>
 </main></SidebarProvider>
 <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent><DialogTitle>{dialog}</DialogTitle><DialogDescription>Esta é uma demonstração da Sala do Aluno. Os conteúdos, notas e registros da escola ainda não estão conectados.</DialogDescription><button className="primary-button" onClick={()=>setDialog(null)}>Voltar para minha sala</button></DialogContent></Dialog>
 </div>
}
