'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {ArrowUpRight,ArrowRight,Check,ChevronLeft,ChevronRight,Clock,Coins,Plus,X,Trash2,Sparkles,SlidersHorizontal,Download,CheckCircle2,Flame,Users} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AppIcon,type IconName} from '@/components/classroom-icon';
import {RoomEditor} from '@/components/room-editor';
import {TeacherPortal} from '@/components/teacher-portal';
import {StudentConnect} from '@/components/student-connect';
import {studentSupabase} from '@/lib/supabase';
import {calculateConnectedMetrics} from '@/lib/connected-flow';
import {activities,themes,fonts,banners,initialState,parseState,STORAGE_KEY,applyPreferences,answerQuestion,submitActivity,score,localDate,type Preferences,type Activity} from '@/lib/classroom';
const navigation:{id:string;label:string;icon:IconName}[]=[{id:'home',label:'Minha sala',icon:'home'},{id:'tasks',label:'Atividades',icon:'tasks'},{id:'calendar',label:'Calendário',icon:'calendar'},{id:'grades',label:'Meu boletim',icon:'grades'},{id:'attendance',label:'Minha presença',icon:'attendance'}];
type ConnectedAssignment={id:string;title:string;subject:string;instructions:string;due_at:string|null;points:number;created_at:string};
type ConnectedSubmission={assignment_id:string;status:'draft'|'submitted';score:number|null;feedback:string|null};
export default function Home(){
 const [state,setState]=useState(initialState),[ready,setReady]=useState(false),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Preferences>(state.preferences),[editorTab,setEditorTab]=useState('theme'),[view,setView]=useState('home'),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState(false),[activeTask,setActiveTask]=useState<Activity|null>(null),[material,setMaterial]=useState<Activity|null>(null),[reminderInput,setReminderInput]=useState(''),[eventOpen,setEventOpen]=useState(false),[eventTitle,setEventTitle]=useState(''),[eventTime,setEventTime]=useState('15:00'),[today,setToday]=useState('2026-09-08'),[selectedDate,setSelectedDate]=useState('2026-09-08'),[month,setMonth]=useState(new Date(2026,8,1)),[showTeacher,setShowTeacher]=useState(false),[showStudentConnect,setShowStudentConnect]=useState(true),[studentAuthReady,setStudentAuthReady]=useState(false),[studentSummary,setStudentSummary]=useState<{name:string;earned:number;possible:number;classCount:number;assignments:ConnectedAssignment[];submissions:ConnectedSubmission[]}|null>(null);
 const stateRef=useRef(state);stateRef.current=state;
 const autoCloseStudentConnect=useRef(true);
 useEffect(()=>{try{setState(parseState(localStorage.getItem(STORAGE_KEY)))}catch{setStorageError(true)}const now=new Date();setToday(localDate(now));setSelectedDate(localDate(now));setMonth(new Date(now.getFullYear(),now.getMonth(),1));setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setStorageError(false)}catch{setStorageError(true)}},[state,ready]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id)},[notice]);
 const refreshStudentSummary=useCallback(async()=>{
  const {data:{session}}=await studentSupabase.auth.getSession();
  if(!session){setStudentSummary(null);setStudentAuthReady(true);return}
  const profileResult=await studentSupabase.from('profiles').select('display_name,role').eq('id',session.user.id).single();
  if(profileResult.data?.role!=='student'){setStudentSummary(null);setStudentAuthReady(true);return}
  const membershipResult=await studentSupabase.from('memberships').select('classroom_id').eq('user_id',session.user.id);
  const classIds=(membershipResult.data??[]).map(item=>item.classroom_id);
  let connectedAssignments:ConnectedAssignment[]=[];
  let connectedSubmissions:ConnectedSubmission[]=[];
  if(classIds.length){
   const assignmentResult=await studentSupabase.from('assignments').select('id,title,subject,instructions,due_at,points,created_at').in('classroom_id',classIds).order('created_at',{ascending:false});
   connectedAssignments=(assignmentResult.data??[]) as ConnectedAssignment[];
   if(connectedAssignments.length){
    const submissionResult=await studentSupabase.from('submissions').select('assignment_id,status,score,feedback').in('assignment_id',connectedAssignments.map(item=>item.id));
    connectedSubmissions=(submissionResult.data??[]) as ConnectedSubmission[];
   }
  }
  const metrics=calculateConnectedMetrics(connectedAssignments,connectedSubmissions);
  setStudentSummary({name:profileResult.data.display_name,earned:metrics.earned,possible:metrics.possible,classCount:classIds.length,assignments:connectedAssignments,submissions:connectedSubmissions});
  setStudentAuthReady(true);
 },[]);
 useEffect(()=>{
  void refreshStudentSummary();
  const {data}=studentSupabase.auth.onAuthStateChange(()=>{void refreshStudentSummary()});
  return()=>data.subscription.unsubscribe();
 },[refreshStudentSummary]);
 useEffect(()=>{if(autoCloseStudentConnect.current&&studentAuthReady&&studentSummary){autoCloseStudentConnect.current=false;setShowStudentConnect(false)}},[studentAuthReady,studentSummary]);
 useEffect(()=>{
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'set_customization_panel',description:'Abre ou fecha o editor. Fechar descarta a prévia sem salvar nem cobrar moedas.',inputSchema:{type:'object',properties:{open:{type:'boolean'}},required:['open'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('open' in input)||typeof input.open!=='boolean')throw new Error('Informe open como booleano.');if(input.open)setDraft({...stateRef.current.preferences});setEditing(input.open);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {open:input.open};}});
 register({name:'read_room_state',description:'Lê as preferências salvas e o progresso local da sala.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({preferences:stateRef.current.preferences,coins:stateRef.current.coins,completed:activities.filter(a=>stateRef.current.attempts[a.id]?.submitted).map(a=>a.id),reminders:stateRef.current.reminders,events:stateRef.current.events})});
 return()=>lifecycle.abort();
 },[]);
 const p=editing?draft:state.preferences,studentName=studentSummary?.name||p.name,theme=themes.find(x=>x.id===p.theme)!,font=fonts.find(x=>x.id===p.font)!,banner=banners.find(x=>x.id===p.banner)!;
 useEffect(()=>{const root=document.documentElement;root.dataset.theme=p.theme;root.dataset.cursor=p.cursor;root.style.setProperty('--primary',theme.color);root.style.setProperty('--primary-soft',theme.soft);root.style.setProperty('--room-font',font.family)},[p.theme,p.cursor,theme,font]);
 function openEditor(tab='theme'){setDraft({...state.preferences});setEditorTab(tab);setEditing(true)}
 function saveEditor(){try{setState(s=>applyPreferences(s,draft));setEditing(false);setNotice('Sua sala foi personalizada!')}catch(e){setNotice((e as Error).message)}}
 function changeView(v:string){setView(v);window.scrollTo({top:0,behavior:'smooth'})}
 const completed=activities.filter(a=>state.attempts[a.id]?.submitted),attendanceToday=state.attendance.includes(today);
 const teacherAssignments=studentSummary?.assignments??[];
 const teacherSubmissions=studentSummary?.submissions??[];
 const teacherDelivered=teacherSubmissions.filter(item=>item.status==='submitted').length;
 const dayEvents=state.events.filter(e=>e.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 function addReminder(e:React.FormEvent){e.preventDefault();if(!reminderInput.trim())return;setState(s=>({...s,reminders:[...s.reminders,{id:crypto.randomUUID(),text:reminderInput.trim(),done:false}]}));setReminderInput('')}
 function addEvent(e:React.FormEvent){e.preventDefault();if(!eventTitle.trim())return;setState(s=>({...s,events:[...s.events,{id:crypto.randomUUID(),date:selectedDate,time:eventTime,title:eventTitle.trim()}]}));setEventOpen(false);setEventTitle('');setNotice('Evento adicionado ao calendário.')}
 function submit(){if(!activeTask)return;try{setState(s=>submitActivity(s,activeTask.id));setNotice('Atividade concluída! Você ganhou 50 moedas.')}catch(e){setNotice((e as Error).message)}}
 const taskCard=(a:Activity)=>{const attempt=state.attempts[a.id];const done=attempt?.submitted,progress=done?100:Math.round((attempt?.answers.filter(x=>x!==null).length??0)/a.questions.length*100);return <article className={`task-card card ${a.color}`} key={a.id}><div className="task-top"><span className="subject-tag">{a.subject}</span><span><Clock size={13}/>{a.minutes} min</span></div><h3>{a.title}</h3><p>{a.description}</p><div className="task-progress"><span>{done?'Concluída':progress?'Em andamento':'Pronta para começar'}</span><strong>{progress}%</strong></div><Progress value={progress} aria-label={`Progresso: ${a.title}`}/><button className={done?'task-button completed':'task-button'} onClick={()=>setActiveTask(a)}>{done?'Ver resultado':progress?'Continuar atividade':'Começar atividade'}{done?<CheckCircle2 size={17}/>:<ArrowRight size={17}/>}</button></article>};
 const teacherTaskCard=(a:ConnectedAssignment)=>{const submission=teacherSubmissions.find(item=>item.assignment_id===a.id),submitted=submission?.status==='submitted',due=a.due_at?new Date(a.due_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'Sem prazo';return <article className="task-card card blue" key={a.id}><div className="task-top"><span className="subject-tag">{a.subject}</span><span><Clock size={13}/>{due}</span></div><h3>{a.title}</h3><p>{a.instructions||'Atividade enviada pelo seu professor.'}</p><div className="task-progress"><span>{submitted?(submission?.score==null?'Enviada':'Corrigida'):'Aguardando sua resposta'}</span><strong>{submitted&&submission?.score!=null?`${submission.score}/${a.points}`:`${a.points} pts`}</strong></div><button className={submitted?'task-button completed':'task-button'} onClick={()=>setShowStudentConnect(true)}>{submitted?'Ver na sala':'Abrir na sala'}<ArrowRight size={17}/></button></article>};
 const calendar=<section className="calendar card"><div className="card-heading"><h2><AppIcon name="calendar" pack={p.icons} size={20}/> Calendário</h2><button className="text-button" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelectedDate(today)}}>Hoje</button></div><div className="month-heading"><strong>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><div><button className="icon-button" aria-label="Mês anterior" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="Próximo mês" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={18}/></button></div></div><div className="calendar-grid">{['D','S','T','Q','Q','S','S'].map((w,i)=><span className="weekday" key={i}>{w}</span>)}{Array.from({length:month.getDay()},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:days},(_,i)=>{const d=localDate(new Date(month.getFullYear(),month.getMonth(),i+1));return <button key={d} className={`${selectedDate===d?'selected':''} ${d===today?'today':''}`} aria-pressed={selectedDate===d} aria-label={new Date(month.getFullYear(),month.getMonth(),i+1).toLocaleDateString('pt-BR',{dateStyle:'full'})} onClick={()=>setSelectedDate(d)}>{i+1}{state.events.some(e=>e.date===d)&&<i/>}</button>})}</div><div className="calendar-events"><div><strong>{new Date(selectedDate+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'})}</strong><button className="icon-button" aria-label="Adicionar evento" onClick={()=>setEventOpen(true)}><Plus size={17}/></button></div>{dayEvents.length?dayEvents.map(e=><div className="event-row" key={e.id}><span>{e.time}</span><strong>{e.title}</strong><button className="icon-button" aria-label={`Excluir evento ${e.title}`} onClick={()=>{setState(s=>({...s,events:s.events.filter(x=>x.id!==e.id)}));setNotice('Evento removido.')}}><Trash2 size={14}/></button></div>):<p className="empty-note">Dia livre para novas descobertas.</p>}</div></section>;
 const reminders=<section className="reminders card"><div className="card-heading"><h2><AppIcon name="bell" pack={p.icons} size={20}/> Lembretes</h2><span className="count-badge">{state.reminders.filter(r=>!r.done).length}</span></div><div className="reminder-list">{state.reminders.map(r=><div className={`reminder-row ${r.done?'done':''}`} key={r.id}><label><Checkbox checked={r.done} onCheckedChange={checked=>setState(s=>({...s,reminders:s.reminders.map(x=>x.id===r.id?{...x,done:!!checked}:x)}))}/><span>{r.text}</span></label><button className="icon-button delete-reminder" aria-label={`Excluir lembrete ${r.text}`} onClick={()=>setState(s=>({...s,reminders:s.reminders.filter(x=>x.id!==r.id)}))}><X size={15}/></button></div>)}{!state.reminders.length&&<p className="empty-note">Tudo organizado! Adicione um novo lembrete.</p>}</div><form className="add-reminder" onSubmit={addReminder}><input aria-label="Novo lembrete" placeholder="Adicionar lembrete…" maxLength={160} value={reminderInput} onChange={e=>setReminderInput(e.target.value)}/><button className="icon-button" aria-label="Salvar lembrete" disabled={!reminderInput.trim()}><Plus size={19}/></button></form></section>;
 if(showTeacher)return <TeacherPortal onClose={()=>{setShowTeacher(false);setShowStudentConnect(true)}}/>;
 if(showStudentConnect)return <StudentConnect pageMode allowClose={!!studentSummary} onClose={()=>setShowStudentConnect(false)} onOpenTeacher={()=>{setShowStudentConnect(false);setShowTeacher(true)}} onChanged={refreshStudentSummary}/>;
 return <div className={`school ${editing?'is-editing':''}`}><SidebarProvider><Sidebar collapsible="none" className="school-sidebar"><a href="./" className="brand" aria-label="Aprendê — página inicial"><span className="brand-icon"><AppIcon name="school" pack={p.icons} size={28}/></span><strong>Aprendê</strong></a><SidebarContent><p className="nav-caption">MEU ESPAÇO</p><nav aria-label="Navegação principal">{navigation.map(n=><button key={n.id} className={`nav-item ${view===n.id?'active':''}`} aria-current={view===n.id?'page':undefined} onClick={()=>changeView(n.id)}><AppIcon name={n.icon} pack={p.icons} size={23}/><span>{n.label}</span>{n.id==='tasks'&&<small>{studentSummary?teacherAssignments.length-teacherDelivered:activities.length-completed.length}</small>}</button>)}</nav><div className="sidebar-customize"><span className="customize-illustration"><AppIcon name="palette" pack={p.icons} size={33}/><Sparkles size={18}/></span><strong>Uma sala com a sua cara.</strong><p>Cores, fontes e muitas possibilidades.</p><button onClick={()=>openEditor()}>Personalizar <ArrowUpRight size={15}/></button></div></SidebarContent><div className="sidebar-profile"><img src={`./avatars/avatar-${p.avatar}.svg`} alt="Seu avatar"/><span><strong>{studentName}</strong><small>{studentSummary?`Aluno conectado · ${studentSummary.classCount} ${studentSummary.classCount===1?'turma':'turmas'}`:`Estudante · Nível ${5+Math.floor(completed.length/3)}`}</small></span><button className="icon-button" onClick={()=>openEditor('profile')} aria-label="Editar meu perfil"><SlidersHorizontal size={16}/></button></div></Sidebar>
 <main className="workspace"><header className="topbar"><div><span className="mobile-wordmark">Aprendê</span><span className="breadcrumb">Sala do Aluno <ChevronRight size={13}/> {navigation.find(n=>n.id===view)?.label}</span><h1>{view==='home'?'Seu espaço, suas conquistas.':navigation.find(n=>n.id===view)?.label}</h1></div><div className="header-actions"><button className="student-connect-button" onClick={()=>setShowStudentConnect(true)}><Users size={18}/><span>{studentSummary?'Minha turma':'Entrar na turma'}</span></button><button className="teacher-mode-button" onClick={()=>setShowTeacher(true)}><AppIcon name="school" pack={p.icons} size={18}/><span>Modo professor</span></button><span className="coin-wallet" title={studentSummary?'Pontos recebidos do professor':'Moedas das missões locais'}><Coins size={20}/><strong>{studentSummary?`${studentSummary.earned}/${studentSummary.possible} pts`:state.coins.toLocaleString('pt-BR')}</strong></span><button className="edit-button" onClick={()=>openEditor()}><SlidersHorizontal size={17}/><span>Personalizar</span></button></div></header>
 {view==='home'&&<><section className={`welcome-banner banner-${p.banner}`}>{banner.src&&<img className="hero-art" src={banner.src} alt="" fetchPriority="high"/>}<div className="welcome-copy"><span className="hero-eyebrow"><span/> PARTIU DESCOBRIR COISAS NOVAS?</span><h2>Oi, {studentName.split(' ')[0]}!<br/>Bora aprender?</h2><p>Escolha uma missão, avance no seu ritmo e colecione conquistas.</p><button onClick={()=>changeView('tasks')}>Começar agora <ArrowUpRight size={18}/></button></div><button className="edit-banner" aria-label="Trocar banner" onClick={()=>openEditor('banner')}><SlidersHorizontal size={17}/></button></section><div className="overview-stats"><div><span className="stat-icon orange"><AppIcon name="tasks" pack={p.icons}/></span><span><strong>{studentSummary?teacherAssignments.length:activities.length-completed.length}</strong><small>{studentSummary?'atividades enviadas pelo professor':'missões esperando por você'}</small></span></div><div><span className="stat-icon green"><AppIcon name="check" pack={p.icons}/></span><span><strong>{studentSummary?`${teacherDelivered} de ${teacherAssignments.length}`:`${completed.length} de ${activities.length}`}</strong><small>{studentSummary?'atividades entregues':'missões concluídas'}</small></span></div><div><span className="stat-icon purple"><AppIcon name="trophy" pack={p.icons}/></span><span><strong>{studentSummary?`${studentSummary.earned} de ${studentSummary.possible} pontos`:'+50 moedas'}</strong><small>{studentSummary?'recebidos do professor':'por missão concluída'}</small></span></div></div></>}
 {(view==='home'||view==='tasks')&&<div className="dashboard"><div className="main-column"><section><div className="section-heading"><div><span className="eyebrow">SEU PRÓXIMO DESAFIO</span><h2>{view==='tasks'?'Todas as atividades':'Atividades da turma'}</h2></div>{view==='home'&&<button className="text-button" onClick={()=>changeView('tasks')}>Ver todas <ArrowRight size={15}/></button>}</div><div className="task-grid">{studentSummary?(teacherAssignments.length?teacherAssignments.slice(view==='home'?0:undefined).map(teacherTaskCard):<p className="empty-note">Nenhuma atividade foi enviada pelo professor ainda.</p>):(view==='home'?activities.slice(0,2):activities).map(taskCard)}</div></section>{studentSummary?<section className="schedule"><div className="section-heading"><div><span className="eyebrow">MATERIAIS DA TURMA</span><h2>Conteúdos enviados</h2></div><span className="small-label">Pelo professor</span></div><div className="schedule-list">{teacherAssignments.length?teacherAssignments.map(a=><div key={a.id} className="schedule-row blue"><span className="schedule-number">•</span><span className="schedule-book"><AppIcon name="tasks" pack={p.icons} size={23}/></span><span className="schedule-details"><strong>{a.title}</strong><small>{a.subject} · {a.points} pontos</small></span><ArrowUpRight size={18}/></div>):<p className="empty-note">Os materiais aparecerão aqui quando o professor enviar uma atividade.</p>}</div></section>:<section className="schedule"><div className="section-heading"><div><span className="eyebrow">PARA IR MAIS LONGE</span><h2>Conteúdos para explorar</h2></div><span className="small-label">No seu ritmo</span></div><div className="schedule-list">{activities.map((a,i)=><button key={a.id} className={`schedule-row ${a.color}`} onClick={()=>setMaterial(a)}><span className="schedule-number">0{i+1}</span><span className="schedule-book"><AppIcon name="tasks" pack={p.icons} size={23}/></span><span className="schedule-details"><strong>{a.title}</strong><small>{a.subject} · Material de apoio</small></span><span className="schedule-time">{a.minutes} min</span><ArrowUpRight size={18}/></button>)}</div></section>}<div className="encouragement"><Sparkles size={18}/><p>{studentSummary?'Novas atividades e recados aparecerão quando o professor enviar.':'Curiosidade ligada? Então você já começou.'}</p></div></div><aside className="secondary-column">{calendar}{!studentSummary&&reminders}</aside></div>}
 {view==='calendar'&&<><div className="page-intro"><h2>Um espaço para seus planos.</h2><p>{studentSummary?'Os lembretes enviados pelo professor aparecerão aqui.':'Escolha um dia e adicione os compromissos que quer lembrar.'}</p></div><div className="calendar-page">{calendar}<div>{!studentSummary&&reminders}<div className="info-card"><AppIcon name="calendar" pack={p.icons} size={28}/><h3>{studentSummary?'Aguardando os próximos recados.':'Do seu jeito, no seu tempo.'}</h3><p>{studentSummary?'Quando o professor publicar um lembrete, ele aparecerá nesta área.':'Seus eventos são pessoais e ficam guardados neste navegador.'}</p></div></div></div></>}
 {view==='grades'&&<><div className="page-intro"><h2>Cada descoberta conta.</h2><p>{studentSummary?'Acompanhe os resultados publicados pelo professor.':'Acompanhe os resultados das atividades que você concluiu aqui.'}</p></div><section className="card grade-card"><div className="card-heading"><h2><AppIcon name="grades" pack={p.icons}/> Resultados das atividades</h2><span className="small-label">Notas publicadas</span></div><div className="grade-list">{studentSummary?(teacherAssignments.filter(a=>teacherSubmissions.some(s=>s.assignment_id===a.id&&s.score!=null)).map(a=>{const submission=teacherSubmissions.find(s=>s.assignment_id===a.id);return <div className="grade-row" key={a.id}><span className="stat-icon blue"><AppIcon name="tasks" pack={p.icons}/></span><span><strong>{a.subject}</strong><small>{a.title}{submission?.feedback?` · ${submission.feedback}`:''}</small></span><strong className="grade-score">{submission?.score}/{a.points}</strong></div>})):<>{activities.map(a=><div className="grade-row" key={a.id}><span className={`stat-icon ${a.color}`}><AppIcon name="tasks" pack={p.icons}/></span><span><strong>{a.subject}</strong><small>{a.title}</small></span><strong className="grade-score">{score(a,state.attempts[a.id])?.toLocaleString('pt-BR')??'—'}</strong><button className="text-button" onClick={()=>setActiveTask(a)}>{state.attempts[a.id]?.submitted?'Revisar':'Começar'}<ArrowRight size={15}/></button></div>)}</>}{studentSummary&&!teacherAssignments.some(a=>teacherSubmissions.some(s=>s.assignment_id===a.id&&s.score!=null))&&<p className="empty-note">Nenhum resultado foi publicado pelo professor ainda.</p>}</div><p className="muted-note">{studentSummary?'As notas e comentários são publicados pelo professor da turma.':'Este boletim reúne suas práticas nesta sala. Não substitui o boletim oficial da escola.'}</p></section></>}
 {view==='attendance'&&<><div className="page-intro"><h2>A constância faz a diferença.</h2><p>Registre os dias em que você reservou um tempo para estudar.</p></div><section className="card attendance-card"><span className="attendance-flame"><Flame size={38}/></span><h2>{attendanceToday?'Bom estudo hoje!':'Já estudou um pouquinho hoje?'}</h2><p>{state.attendance.length} {state.attendance.length===1?'dia registrado':'dias registrados'} no seu espaço de estudos.</p><button className="primary-button" disabled={attendanceToday} onClick={()=>{setState(s=>s.attendance.includes(today)?s:{...s,attendance:[...s.attendance,today]});setNotice('Seu dia de estudo foi registrado.')}}>{attendanceToday?<><Check size={18}/> Presença registrada</>:<>Registrar meu estudo de hoje <Plus size={18}/></>}</button><div className="attendance-days">{[...state.attendance].sort().reverse().map(d=><span key={d}><CheckCircle2 size={16}/>{new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{dateStyle:'long'})}</span>)}</div><p className="muted-note">Registro pessoal de estudo, independente da chamada oficial da escola.</p></section></>}
 <footer className="workspace-footer"><span><AppIcon name="school" pack={p.icons} size={17}/></span><span>{storageError?'Não foi possível salvar no navegador. Mantenha esta página aberta.':ready?'Seu progresso fica salvo neste navegador.':'Carregando seu espaço…'}</span></footer></main></SidebarProvider>
 {editing&&<RoomEditor key={editorTab} open={editing} onClose={()=>setEditing(false)} draft={draft} onChange={setDraft} onSave={saveEditor} owned={state.owned} coins={state.coins} initialTab={editorTab}/>}
 {showStudentConnect&&<StudentConnect pageMode allowClose={studentAuthReady&&!!studentSummary} onClose={()=>setShowStudentConnect(false)} onOpenTeacher={()=>{setShowStudentConnect(false);setShowTeacher(true)}} onChanged={refreshStudentSummary}/>}
 <Dialog open={!!activeTask} onOpenChange={v=>{if(!v)setActiveTask(null)}}><DialogContent className="activity-dialog"><DialogTitle>{activeTask?.title}</DialogTitle><DialogDescription>{activeTask?.subject} · {state.attempts[activeTask?.id??'']?.submitted?'Resultado e revisão':'Responda às perguntas. Suas respostas são salvas automaticamente.'}</DialogDescription>{activeTask&&<div className="quiz-content">{activeTask.questions.map((q,i)=>{const attempt=state.attempts[activeTask.id];const answer=attempt?.answers[i];return <section className="quiz-question" key={i}><h3><span>{i+1}</span>{q.prompt}</h3><RadioGroup value={answer==null?'':String(answer)} onValueChange={v=>{try{setState(s=>answerQuestion(s,activeTask.id,i,Number(v)))}catch(e){setNotice((e as Error).message)}}} aria-label={`Questão ${i+1}`} disabled={attempt?.submitted}>{q.options.map((option,j)=><label key={j} className={`quiz-option ${attempt?.submitted&&j===q.answer?'correct':''} ${attempt?.submitted&&j===answer&&j!==q.answer?'incorrect':''}`}><RadioGroupItem value={String(j)}/><span>{option}</span>{attempt?.submitted&&j===q.answer&&<Check size={17}/>}</label>)}</RadioGroup>{attempt?.submitted&&<p className="answer-explanation">{q.explanation}</p>}</section>})}{state.attempts[activeTask.id]?.submitted?<div className="quiz-result"><AppIcon name="trophy" pack={p.icons} size={30}/><div><strong>Seu resultado: {score(activeTask,state.attempts[activeTask.id])?.toLocaleString('pt-BR')} / 10</strong><p>Confira as explicações e continue aprendendo.</p></div></div>:<button className="primary-button" disabled={(state.attempts[activeTask.id]?.answers.filter(x=>x!==null).length??0)!==activeTask.questions.length} onClick={submit}>Concluir atividade <span>+50 <Coins size={16}/></span></button>}</div>}</DialogContent></Dialog>
 <Dialog open={!!material} onOpenChange={v=>{if(!v)setMaterial(null)}}><DialogContent className="material-dialog"><DialogTitle>{material?.title}</DialogTitle><DialogDescription>{material?.subject} · Material de apoio</DialogDescription><article className="lesson-content">{material?.lesson.map((para,i)=><p key={i}>{para}</p>)}</article><div className="material-actions"><button className="secondary-button" onClick={()=>window.print()}><Download size={16}/> Imprimir / salvar PDF</button><button className="primary-button" onClick={()=>{setActiveTask(material);setMaterial(null)}}>Praticar <ArrowRight size={17}/></button></div></DialogContent></Dialog>
 <Dialog open={eventOpen} onOpenChange={setEventOpen}><DialogContent><DialogTitle>Novo evento</DialogTitle><DialogDescription>{new Date(selectedDate+'T12:00:00').toLocaleDateString('pt-BR',{dateStyle:'long'})}</DialogDescription><form className="event-form" onSubmit={addEvent}><label className="form-label">O que você quer lembrar?<input className="text-input" autoFocus required maxLength={160} value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Ex.: Estudar para a prova"/></label><label className="form-label">Horário<input className="text-input" type="time" required value={eventTime} onChange={e=>setEventTime(e.target.value)}/></label><button className="primary-button"><Plus size={17}/> Adicionar evento</button></form></DialogContent></Dialog>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button className="icon-button" aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 </div>
}
