export const STORAGE_KEY = 'aprende-v1';
export const themes = [
 {id:'sunrise',name:'Pôr do sol',color:'#dd571b',soft:'#fff0e5',swatches:['#f87935','#ffd78e','#f4efe9'],price:0},
 {id:'lavender',name:'Lavanda',color:'#7750c5',soft:'#f0e9fc',swatches:['#8a65d4','#d8c9f6','#f3eefc'],price:100},
 {id:'ocean',name:'Oceano',color:'#067d9f',soft:'#e4f5fa',swatches:['#1099ba','#abe8ef','#e8f6fb'],price:100},
 {id:'forest',name:'Jardim',color:'#28805a',soft:'#e6f4eb',swatches:['#45a779','#bfdfb5','#f1f7ed'],price:100},
 {id:'rose',name:'Rosa pop',color:'#c13777',soft:'#ffebf3',swatches:['#e65996','#f8b6d5','#fff1f7'],price:100},
 {id:'midnight',name:'Meia-noite',color:'#ac94ff',soft:'#332a4b',swatches:['#a489f0','#302641','#181622'],price:300},
] as const;
export const fonts=[{id:'dm',name:'DM Sans',family:'"DM Sans Variable", sans-serif',detail:'Limpa e contemporânea',price:0},{id:'nunito',name:'Nunito',family:'"Nunito Variable", sans-serif',detail:'Arredondada e amigável',price:100},{id:'lora',name:'Lora',family:'"Lora Variable", serif',detail:'Um toque de literatura',price:100},{id:'space',name:'Space Grotesk',family:'"Space Grotesk Variable", sans-serif',detail:'Geométrica e criativa',price:100}] as const;
export const banners=[{id:'creative',name:'Mundo de ideias',src:'./banners/creative.png',price:0},{id:'cosmos',name:'Além das estrelas',src:'./banners/cosmos.png',price:250},{id:'aurora',name:'Aurora',src:'',price:100},{id:'candy',name:'Doce criatividade',src:'',price:100}] as const;
export const iconPacks=[{id:'lucide',name:'Lucide',detail:'Traços leves',price:0},{id:'duotone',name:'Phosphor Duo',detail:'Duas camadas de cor',price:150},{id:'bold',name:'Phosphor Bold',detail:'Traços marcantes',price:150},{id:'fill',name:'Phosphor Fill',detail:'Formas preenchidas',price:150}] as const;
export const cursors=[{id:'default',name:'Clássico',price:0},{id:'star',name:'Estrela',price:50},{id:'heart',name:'Coração',price:50},{id:'sparkle',name:'Brilho',price:50},{id:'pointer',name:'Neon',price:50}] as const;
export type Preferences={theme:string;font:string;banner:string;icons:string;cursor:string;avatar:number;name:string};
export const defaultPreferences:Preferences={theme:'sunrise',font:'dm',banner:'creative',icons:'duotone',cursor:'default',avatar:0,name:'Ana Silva'};
export const catalogs={theme:themes,font:fonts,banner:banners,icons:iconPacks,cursor:cursors};
export type Question={prompt:string;options:string[];answer:number;explanation:string};
export type Activity={id:string;subject:string;title:string;description:string;color:string;minutes:number;questions:Question[];lesson:string[]};
export const activities:Activity[]=[
 {id:'fractions',subject:'Matemática',title:'Uma parte de um todo',description:'Vamos praticar frações?',color:'orange',minutes:8,questions:[{prompt:'Uma pizza tem 8 fatias. Ana comeu 2. Que fração ela comeu?',options:['1/2','1/4','3/4'],answer:1,explanation:'2 de 8 fatias = 2/8. Dividindo o numerador e o denominador por 2, temos 1/4.'},{prompt:'Quanto é 1/2 + 1/4?',options:['2/6','1/6','3/4'],answer:2,explanation:'Escreva 1/2 como 2/4. Então, 2/4 + 1/4 = 3/4.'},{prompt:'Qual fração é equivalente a 2/3?',options:['4/6','2/6','3/2'],answer:0,explanation:'Multiplicando o numerador e o denominador por 2: 2/3 = 4/6.'}],lesson:['Uma fração representa uma parte de um todo. O denominador mostra em quantas partes iguais o todo foi dividido. O numerador mostra quantas dessas partes estamos considerando.','Por exemplo, 3/4 significa três de quatro partes iguais. Frações equivalentes representam a mesma quantidade: 1/2 e 2/4 são equivalentes.','Para somar frações com denominadores diferentes, primeiro encontre um denominador comum. Assim, 1/2 + 1/4 se transforma em 2/4 + 1/4 = 3/4.']},
 {id:'reading',subject:'Português',title:'Histórias que ensinam',description:'Leia, imagine e descubra.',color:'purple',minutes:6,questions:[{prompt:'“Lia plantou uma semente e cuidou dela todos os dias. Depois de algumas semanas, viu a primeira flor.” O que aconteceu primeiro?',options:['A flor apareceu.','Lia plantou uma semente.','Lia colheu a flor.'],answer:1,explanation:'O texto começa com o plantio da semente, antes dos cuidados e do surgimento da flor.'},{prompt:'No texto, a expressão “todos os dias” indica:',options:['Lugar','Dúvida','Frequência'],answer:2,explanation:'A expressão informa com que frequência Lia cuidava da planta.'},{prompt:'Qual título combina melhor com a história?',options:['O cuidado de Lia','Uma viagem ao mar','A festa na escola'],answer:0,explanation:'O cuidado de Lia é o tema central da história: ela plantou e acompanhou o crescimento.'}],lesson:['Ler é mais do que reconhecer palavras: é relacionar ideias. Antes de responder, procure no texto as informações que sustentam sua resposta.','Observe a ordem dos acontecimentos. Palavras como “antes”, “depois” e “por fim” ajudam a entender a sequência de uma história.','Lia plantou uma semente e cuidou dela todos os dias. Depois de algumas semanas, viu a primeira flor. O texto mostra que o cuidado frequente acompanha o crescimento da planta.']},
 {id:'history',subject:'História',title:'Pistas do passado',description:'Conheça as fontes históricas.',color:'pink',minutes:7,questions:[{prompt:'Qual destes objetos pode ser uma fonte histórica?',options:['Uma fotografia antiga','Apenas um livro novo','Somente um computador'],answer:0,explanation:'Fotografias antigas registram pessoas, lugares e costumes e podem ser estudadas como fontes históricas.'},{prompt:'Um relato de uma pessoa sobre sua infância é uma fonte:',options:['Geográfica','Oral','Climática'],answer:1,explanation:'Relatos e entrevistas são exemplos de fontes orais.'},{prompt:'Por que comparar diferentes fontes?',options:['Para escolher a mais bonita','Para ignorar as diferenças','Para compreender diferentes pontos de vista'],answer:2,explanation:'A comparação permite identificar perspectivas, divergências e informações complementares.'}],lesson:['Os historiadores investigam o passado usando fontes históricas. Fotografias, cartas, objetos, construções e relatos são alguns exemplos.','Cada fonte foi produzida em um contexto. É importante perguntar: quem a criou? Quando? Com qual finalidade?','Comparar diferentes fontes ajuda a entender o passado de forma mais completa. Uma fotografia e uma entrevista podem trazer pontos de vista diferentes sobre o mesmo acontecimento.']}
];
export type Reminder={id:string;text:string;done:boolean};
export type CalendarEvent={id:string;date:string;time:string;title:string};
export type Attempt={answers:(number|null)[];submitted:boolean};
export type AppState={version:2;preferences:Preferences;coins:number;owned:string[];attempts:Record<string,Attempt>;reminders:Reminder[];events:CalendarEvent[];attendance:string[]};
export function initialState():AppState{return {version:2,preferences:{...defaultPreferences},coins:2450,owned:['icons:duotone'],attempts:{},reminders:[{id:'r1',text:'Separar o material para amanhã',done:false},{id:'r2',text:'Praticar frações',done:false},{id:'r3',text:'Ler por 15 minutos',done:true}],events:[],attendance:[]};}
export function preferenceCost(p:Preferences,owned:string[]){return Object.entries(catalogs).reduce((sum,[key,values])=>{const id=p[key as keyof Preferences];const item=values.find(v=>v.id===id);return sum+(item&&!owned.includes(`${key}:${id}`)?item.price:0)},0)}
export function validPreferences(value:unknown):Preferences{const result={...defaultPreferences};if(!value||typeof value!=='object')return result;const v=value as Record<string,unknown>;for(const [key,items] of Object.entries(catalogs)){if(items.some(x=>x.id===v[key]))(result as unknown as Record<string,unknown>)[key]=v[key];}if(typeof v.name==='string'&&v.name.trim())result.name=v.name.trim().slice(0,40);if(Number.isInteger(v.avatar)&&Number(v.avatar)>=0&&Number(v.avatar)<8)result.avatar=Number(v.avatar);return result;}
export function applyPreferences(state:AppState,p:Preferences):AppState{const preferences=validPreferences(p);const cost=preferenceCost(preferences,state.owned);if(cost>state.coins)throw new Error('Moedas insuficientes. Escolha menos itens ou conclua uma atividade.');return {...state,preferences,coins:state.coins-cost,owned:[...new Set([...state.owned,...Object.keys(catalogs).map(k=>`${k}:${preferences[k as keyof Preferences]}`)])]};}
export function answerQuestion(state:AppState,id:string,index:number,answer:number):AppState{const activity=activities.find(a=>a.id===id);if(!activity||!activity.questions[index]||!Number.isInteger(answer)||answer<0||answer>=activity.questions[index].options.length)throw new Error('Resposta inválida.');const old=state.attempts[id];if(old?.submitted)throw new Error('Atividade já concluída.');const answers=old?[...old.answers]:activity.questions.map(()=>null);answers[index]=answer;return {...state,attempts:{...state.attempts,[id]:{answers,submitted:false}}};}
export function submitActivity(state:AppState,id:string):AppState{const activity=activities.find(a=>a.id===id),attempt=state.attempts[id];if(!activity||!attempt||attempt.answers.length!==activity.questions.length||attempt.answers.some(a=>a===null))throw new Error('Responda todas as perguntas antes de concluir.');if(attempt.submitted)return state;return {...state,coins:state.coins+50,attempts:{...state.attempts,[id]:{...attempt,submitted:true}}};}
export function score(activity:Activity,attempt?:Attempt){return attempt?.submitted?Math.round(activity.questions.reduce((n,q,i)=>n+(attempt.answers[i]===q.answer?1:0),0)/activity.questions.length*100)/10:null;}
export function parseState(raw:string|null):AppState{const base=initialState();if(!raw)return base;try{const d=JSON.parse(raw);if(!d||d.version!==2)return base;const text=(s:unknown)=>typeof s==='string'&&s.length<=200;const iso=(s:unknown)=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s);base.preferences=validPreferences(d.preferences);if(Number.isInteger(d.coins)&&d.coins>=0&&d.coins<=1000000)base.coins=d.coins;if(Array.isArray(d.owned))base.owned=d.owned.filter((s:unknown)=>typeof s==='string');if(Array.isArray(d.reminders))base.reminders=d.reminders.filter((r:Reminder)=>r&&text(r.id)&&text(r.text)&&typeof r.done==='boolean').slice(0,100);if(Array.isArray(d.events))base.events=d.events.filter((e:CalendarEvent)=>e&&text(e.id)&&iso(e.date)&&text(e.title)&&typeof e.time==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time)).slice(0,100);if(Array.isArray(d.attendance))base.attendance=[...new Set<string>(d.attendance.filter(iso))];for(const a of activities){const attempt=d.attempts?.[a.id];if(attempt&&Array.isArray(attempt.answers)&&attempt.answers.length===a.questions.length&&attempt.answers.every((v:unknown,i:number)=>v===null||(Number.isInteger(v)&&Number(v)>=0&&Number(v)<a.questions[i].options.length)))base.attempts[a.id]={answers:attempt.answers,submitted:attempt.submitted===true&&attempt.answers.every((v:unknown)=>v!==null)};}return base;}catch{return base}}
export function localDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
